GEMINI_API_KEY="AIzaSyA1ByqZkw0npZ3cy0y5gASYmrLjoEf2DWE"
SERPAPI_API_KEY="4d6c24ac974242e12d6fc0b023cae41a768f65e02d7c0f60841710abedf00eef"
AZURE_OPENAI_API_KEY="Fs2m23tC10YzLZkVgxDQqWpZWgCGe2f9170RGWq7zSejWPqEG4jqJQQJ99BFACHYHv6XJ3w3AAAAACOGpwCo"
AZURE_OPENAI_ENDPOINT="https://canli-mc0ii7d5-eastus2.openai.azure.com/"
AZURE_OPENAI_DEPLOYMENT="gpt-4o"

GOOGLE_APPLICATION_CREDENTIALS="/Users/ecemzeynepiscanli/PycharmProjects/GEMINI TENDER SPESIFICATION/KEYS/stable-dogfish-461111-m8-a2aa9b8d2955.json"
PROJECT_ID="stable-dogfish-461111-m8"
LOCATION="us-east5"
LLAMA_MODEL="meta/llama-4-maverick-17b-128e-instruct-maas"
